apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ksm-and-node-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: 1.23/charts/01-ksm-and-node-exporter
    repoURL: 'https://github.com/vasiliy-grinko/devops-tools'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
