---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-go-prog
spec:
  rules:
  - host: www.bart.team
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sample-go-prog
            port: 
              name: http
              