apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
spec:
  destination:
    name: ''
    namespace: pgo
    server: 'https://kubernetes.default.svc'
  source:
    path: 1.23/05-postgresql/pgadmin/manifestst
    repoURL: 'https://github.com/vasiliy-grinko/devops-tools'
    targetRevision: HEAD
  project: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
