---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-router-pvc
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
