k8s_masters:
  hosts:
    # Control nodes
    control1.bart.team:
    control2.bart.team:
    control3.bart.team:
k8s_workers:
  hosts:
    # Worker nodes
    worker1.bart.team:
    worker2.bart.team:
    worker3.bart.team:
    db1.bart.team:
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
